apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestTask
  labels:
    app: requestTask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestTask
  template:
    metadata:
      labels:
        app: requestTask
    spec:
      containers:
        - name: requestTask
          image: username/requestTask:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5